[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "audio_samples"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "librosa>=0.11.0",
    "matplotlib>=3.7.5",
    "numpy>=1.24.4",
    "scikit-learn>=1.3.2",
    "seaborn>=0.13.2",
    "soundfile>=0.13.1",
]
[tool.maturin]
features = ["pyo3/extension-module"]
